name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: go-minimal-api:latest

      - name: Run AI Code Reviewer
        run: docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} vitormoschetta/go-minimal-api:latest ./app